# Generated by Django 4.2.2 on 2023-07-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='news_images/'),
        ),
    ]
