# Generated by Django 4.2.2 on 2023-06-29 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(choices=[('Калькуляция', 'Калькуляция'), ('Безналичный расчет', 'Безналичный расчет')], max_length=20)),
                ('Tariff', models.CharField(choices=[('Стандарт', 'Стандарт'), ('Оптиум', 'Оптиум'), ('Максимум', 'Максимум')], default=False, max_length=10)),
                ('Number_of_workplaces', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('Information_base_volume', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('Cashier_workplace', models.BooleanField(default=False)),
                ('Cashier_quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('Accountant_workplace', models.BooleanField(default=False)),
                ('Accountant_quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('Pos', models.BooleanField(default=False)),
                ('Payment_terminal', models.BooleanField(default=False)),
                ('Transport_Card', models.BooleanField(default=False)),
                ('SKUD', models.BooleanField(default=False)),
                ('Period', models.CharField(choices=[('3 мес.', '3 мес.'), ('6 мес.', '6 мес.'), ('9 мес.', '9 мес.'), ('12 мес.', '12 мес.')], default=False, max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
