# Generated by Django 4.2.2 on 2023-06-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultationform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('choice', models.CharField(choices=[('Детский сад/школа', 'Option 1'), ('Колледж/Университет', 'Option 2'), ('Комбинат питания', 'Option 3'), ('Другое', 'Option 4')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
